language: python
python:
  - "2.7"
services:
  - postgresql
install: "pip install -r requirements.txt"
before_script: "cp nadine/local_settings.example nadine/local_settings.py"
script: ./manage.py test
notifications:
  email:
    recipients:
      - jacob@officenomads.com
    on_success: change
    on_failure: always
